import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { GoogleGenAI } from '@google/genai';
import fs from 'fs';
import path from 'path';

// Initialize Gemini
// Ensure GEMINI_API_KEY is in your .env
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

// Helper to read Prisma schema
function getPrismaSchema() {
  try {
    const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
    return fs.readFileSync(schemaPath, 'utf-8');
  } catch (error) {
    console.error('Error reading prisma schema:', error);
    return 'Error loading schema';
  }
}

export async function POST(req: Request) {
  try {
    const { query, lang, userName, history } = await req.json();

    if (!query) {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json({ 
        answer: lang === 'ar' 
          ? 'مفتاح API الخاص بـ Gemini غير متوفر. يرجى إضافته في ملف .env (GEMINI_API_KEY)' 
          : 'Gemini API key is missing. Please add it to .env (GEMINI_API_KEY).' 
      }, { status: 500 });
    }

    const schema = getPrismaSchema();

    // Step 1: Text to SQL
    const sqlPrompt = `
You are an expert SQL developer for a SQLite database.
Given the following Prisma Schema for a Marine Conservation platform:

\`\`\`prisma
${schema}
\`\`\`

${history && history.length > 0 ? "--- CONVERSATION HISTORY ---\n" + history.map((m: any) => `${m.role.toUpperCase()}: ${m.content}`).join("\n") + "\n--------------------------\n" : ""}
The user (named ${userName}) asked: "${query}"

Write a valid SQLite SELECT query to answer this question.
RULES:
1. ONLY return a raw SQLite query. No markdown formatting, no explanations, no \`\`\`sql blocks. Just the query string.
2. DO NOT include any destructive operations (INSERT, UPDATE, DELETE). ONLY SELECT.
3. Handle date queries intelligently (e.g. last 10 days, this month) using SQLite datetime functions.
4. If joining tables, ensure you use the exact table names generated by Prisma (usually identical to the model name, e.g., "Patrol", "Violation").
5. The user's name is ${userName}.
`;

    const sqlResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-lite',
      contents: sqlPrompt,
    });

    let rawSql = sqlResponse.text?.trim() || '';
    
    // Clean up potential markdown formatting if Gemini still included it
    rawSql = rawSql.replace(/^```sql\\s*/i, '').replace(/\\s*```$/i, '');
    rawSql = rawSql.replace(/^```/i, '').replace(/```$/i, '');

    console.log("Generated SQL:", rawSql);

    if (!rawSql.toUpperCase().startsWith('SELECT')) {
        throw new Error('Generated SQL is not a SELECT query: ' + rawSql);
    }

    // Step 2: Execute SQL
    let queryResults: any;
    try {
      queryResults = await prisma.$queryRawUnsafe(rawSql);
      
      // Convert BigInts to strings if any exist in the raw response
      const stringifiedResults = JSON.stringify(queryResults, (key, value) =>
          typeof value === 'bigint' ? value.toString() : value
      );
      queryResults = JSON.parse(stringifiedResults);

    } catch (dbError: any) {
      console.error("Database error executing generated SQL:", dbError);
      return NextResponse.json({ 
        answer: lang === 'ar' 
          ? 'عذراً، حدث خطأ أثناء استخراج البيانات من قاعدة البيانات. يرجى إعادة صياغة السؤال.' 
          : 'Sorry, an error occurred while extracting data. Please rephrase your question.',
        sqlQuery: rawSql
      }, { status: 200 }); // Return 200 so UI shows it as an AI response
    }

    // Step 3: Result to Natural Language & Chart Config
    const responsePrompt = `
You are "المساعد الذكي الموحد" (Unified AI Assistant) in a Marine Conservation platform (Red Sea Reserves).
You speak with the user whose name is ${userName}.

${history && history.length > 0 ? "--- CONVERSATION HISTORY ---\n" + history.map((m: any) => `${m.role.toUpperCase()}: ${m.content}`).join("\n") + "\n--------------------------\n" : ""}
The user asked: "${query}"
The database executed this SQL query: ${rawSql}
And returned this JSON data:
\`\`\`json
${JSON.stringify(queryResults, null, 2)}
\`\`\`

TASK:
1. Analyze the data and write a natural, professional response to the user in ${lang === 'ar' ? 'Arabic' : 'English'}.
2. Be helpful, concise, and accurate based on the data. Use the user's name.
3. If the data contains multiple rows or categories that would look good in a chart, provide a chart configuration.

OUTPUT FORMAT: You MUST return a pure JSON object (without markdown blocks) with this exact structure:
{
  "answer": "Your natural language response here",
  "chartConfig": null // OR an object like below if a chart is useful
}

Example chartConfig:
{
  "type": "bar", // "bar", "pie", or "line"
  "data": [ {"name": "Category A", "value": 10}, {"name": "Category B", "value": 20} ],
  "xAxisKey": "name",
  "series": [ {"key": "value", "color": "#0088FE", "name": "Count"} ]
}
`;

    const finalResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-lite',
      contents: responsePrompt,
      config: {
        responseMimeType: "application/json"
      }
    });

    const resultText = finalResponse.text || '{}';
    const parsedResult = JSON.parse(resultText);

    return NextResponse.json({
      answer: parsedResult.answer || (lang === 'ar' ? 'تم العثور على البيانات ولكن تعذر تنسيقها.' : 'Data found but could not be formatted.'),
      chartConfig: parsedResult.chartConfig || null,
      sqlQuery: rawSql // Included for debugging/transparency
    });

  } catch (error: any) {
    console.error('AI Assistant API Error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
